### ISSUE TITLE
Reserve Support.

### ISSUE THREAD

**Issue by creatorfromhell** [MrLetsplay2003/MineBay#3]
I am the developer of the plugin Reserve, a modern economy API with modern economy features in mind. I'm currently looking for developers to add support for it.

Link: https://www.spigotmc.org/resources/reserve.50739/

Thank you,
   creatorfromhell

**Comment by MrLetsplay2003** [comment]
1. Sorry for responding literally 3 months after your question/suggestion (I don't check this very often and must've overlooked the notification)
2. Yes, i wouldn't mind implementing it. I'll see how it goes and come back if there are any issues. I'll close the issue afterwards

**Comment by MrLetsplay2003** [comment]
Support for Reserve is now implemented (v3.0b) & should work

**Comment by creatorfromhell** [comment]
Cheers.
