### ISSUE TITLE
InventoryClickEvent problem.

### ISSUE THREAD

**Issue by MCGuRon** [MrLetsplay2003/MineBay#5]
[12:10:28 ERROR]: Could not pass event InventoryClickEvent to MrCore_BukkitImpl v3.4.2
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null

This is only one error what i get. Can you fix this? Sorry for bad Eng.
I'm using default Paper.

**Comment by MrLetsplay2003** [comment]
What did you click on to produce the error?

**Comment by MCGuRon** [comment]
On green flag for confirm purchase of new "Auction room". They do nothing, and sending error in console.

**Comment by MrLetsplay2003** [comment]
I don't seem to get that error when I try it. Did you change something in the config before trying to buy the auction room?

**Comment by MCGuRon** [comment]
I just installed your plugin on a clean empty server to configure it for my server, and before I change anything, I study the plugin, and this error occurred while studying the plugin. I have a kernel on 1.16.5 Paper, with several plugins, for the test. Your plugin doesn't conflict, works well overall, but it throws the error above. I don't know what the problem is, but this error is there.

**Comment by MrLetsplay2003** [comment]
I just set up a server on Paper 1.16.5 with MineBay, Vault and [GemsEconomy](https://www.spigotmc.org/resources/gemseconomy.19655/) (with the `vault` option enabled in the GemsEconomy config). I created a currency with a name and gave myself some of that currency, and everything appears to be working fine when buying a room.
Are you using a Vault-compatible economy plugin? If so, does the currency of that plugin have a name? Because if it doesn't, that could be causing the issue

**Comment by MrLetsplay2003** [comment]
Also, can you paste the entire stack trace (includin the `at ...`)?

**Comment by MCGuRon** [comment]
I think it's easier for me to throw you the test server logs. I have a plugin for economics for the vault plugin.
[latest.log](https://github.com/MrLetsplay2003/MineBay/files/7833380/latest.log)

**Comment by MrLetsplay2003** [comment]
It seems that the economy plugin you're using doesn't give error messages, which is causing the issues in MineBay. I'll upload a fix for that shortly

**Comment by MrLetsplay2003** [comment]
Okay, I've just uploaded a new version which should fix the issue.
Could you please tell me which economy plugin you're using so I can see whether there could be other issues with it?

**Comment by MCGuRon** [comment]
Ok, now I'll check how the plugin will work.

**Comment by MCGuRon** [comment]
I am using the PEconomy plugin: https://www.spigotmc.org/resources/peconomy.73827/

And yes, now the plugin is reporting an error to me, but it is unknown.
Unfortunately, your fix didn't help. I can tell right away that everything is fine with the economy plugin, other plugins see it and use it.

**Comment by MrLetsplay2003** [comment]
The plugin will now report an "Unknown error" if the economy plugin doesn't provide a proper error message. I can't really do more about that, because the economy plugin is usually responsible for handling error messages. The most likely issue why you're getting an error message is because you have insufficient funds or have not configured the economy plugin correctly (e.g. by adding a currency)

**Comment by MrLetsplay2003** [comment]
To get a more descriptive message, you could either ask the author of the economy plugin to fix the missing messages or switch to another economy plugin

**Comment by MrLetsplay2003** [comment]
After some testing with PEconomy, I seem to be getting the same issue, even though I have enough funds and the plugin appears to be configured correctly. I don't know what's causing it though

**Comment by MrLetsplay2003** [comment]
Okay, after some digging I found the issue. PEconomy actually looks for the currency to use with Vault in the wrong config file. If you copy the `vault` block from `currencies.yml` to `config.yml`, it will work as intended and state in the console:
`[PEconomy] Currency 'dollars' will be used for Vault economy.`

If you don't, you will get an error saying
`[PEconomy] Vault default currency is not specified, ignoring it.`
and it will give you the "Unknown error" when trying to buy something on MineBay

Edit: I opened an [issue](https://github.com/SoKnight/PEconomy/issues/6) on the PEconomy GitHub repository about this

**Comment by MCGuRon** [comment]
I close this thead. Thanks for help. This problem in PEconomy plugin, but on older version all works fine. I'm sorry for taking your time.
