### ISSUE TITLE
Command Aliases problems.

### ISSUE THREAD

**Issue by MCGuRon** [MrLetsplay2003/MineBay#6]
Alias commands do not work, although they are written correctly. I am attaching the config, in which you can see that they are correctly registered. Please help me to solve this problem.
[config.yml.tar.gz](https://github.com/MrLetsplay2003/MineBay/files/8042371/config.yml.tar.gz)
.

**Comment by MrLetsplay2003** [comment]
It seems you forgot to add the slash in front of the command aliases (e.g. `/auc` instead of just `auc`). When I add them, it works for me.

**Comment by MCGuRon** [comment]
Command is working, but, don't tab-completing now. And after this command, still showing minebay command help. Can you please add tab-completing and command changing in command help list? Or fix just tab completer.

**Comment by MrLetsplay2003** [comment]
I'm aware of the tab-completing issue. I will fix that when I have time, but it might take some effort

**Comment by MCGuRon** [comment]
I'm close the issue, but I hope, you fix this. And add the alias command to showing in help list.

**Comment by MrLetsplay2003** [comment]
I've just released an update which should fix the issue, thank you for reporting it
